# Generated by Django 4.2.2 on 2023-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('std', models.CharField(max_length=20)),
                ('addmision_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
